### ISSUE TITLE
[BUG] systemctl restart numad failed when SELINUX is on 

### ISSUE THREAD

**Issue by ruihongw** [openEuler-Computing/numad#1]
Greetings,
I have recently encountered an error when restarting numad with Selinux is forced.
Arch: x86_64
When Selinux is down, the operation is alright.
Please check if it is a common bug.
Thanks.

● numad.service - numad - The NUMA daemon that manages application locality.
   Loaded: loaded (/usr/lib/systemd/system/numad.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2020-09-16 11:08:09 CST; 2min 17s ago
     Docs: man:numad
  Process: 618176 ExecStart=/usr/bin/numad -i 15 (code=exited, status=1/FAILURE)

Sep 16 11:08:09 localhost.localdomain systemd[1]: Starting numad - The NUMA daemon that manages application locality....
Sep 16 11:08:09 localhost.localdomain numad[618176]: Wed Sep 16 11:08:09 2020: Cannot open numad log file (errno: 13) -- using stderr
Sep 16 11:08:09 localhost.localdomain numad[618176]: Wed Sep 16 11:08:09 2020: msgget failed
Sep 16 11:08:09 localhost.localdomain systemd[1]: numad.service: Control process exited, code=exited, status=1/FAILURE
Sep 16 11:08:09 localhost.localdomain systemd[1]: numad.service: Failed with result 'exit-code'.
Sep 16 11:08:09 localhost.localdomain systemd[1]: Failed to start numad - The NUMA daemon that manages application locality..
[root@localhost testEL_Numad_FUN.001]# systemctl start numad
Job for numad.service failed because the control process exited with error code.

**Comment by liqingqing1229** [comment]
@l00382548  please deal with this question.

**Comment by luochenglcs** [comment]
The permission policy of the selinux /var/log file causes the failure to create numad logs. In this case, disable the selinux.

**Comment by luochenglcs** [comment]
The permission policy of the selinux /var/log file causes the failure to create numad logs. In this case, disable the selinux.

**Comment by luochenglcs** [comment]
The permission policy of the selinux /var/log file causes the failure to create numad logs. In this case, disable the selinux.
